### ISSUE TITLE
Service provider not ready for use

### ISSUE THREAD

**Issue by roarkmccolgan** [ggdx/LaravelInsightly#1]
Hi,

Just wondering why the Readme states:
"This service provider is not ready for use yet."?

Are we able to use this package or is it still in development?

Thanks!

**Comment by ggdx** [comment]
Hi
I am aware of a number of issues, mostly tiny ones that need ironing out. I was hired on other projects so didn't have time to deal with these.

I'll wrap it up shortly.

**Comment by roarkmccolgan** [comment]
Great, thanks for letting me know.
I look forward to giving it a run when ready...
